blueprint:
  name: Motion-activated Light and Lux
  description: Turn on a light when motion is detected. and Lux value is below Value.
  domain: automation
  # source_url: https://github.com/glissak/blueprints/motion_light_lux.yaml
  input:
    motion_entity:
      name: Presence Sensor
      selector:
        entity:
          domain: binary_sensor
    switch_target:
      name: Light
      description: The switch to turn on
      selector:
        target:
          entity:
            domain: switch
    lux_threshold:
      name: Lux value threshold
      description: Lux value threshold to triger the light if below.
      default: 70
      selector:
        number:
          min: 0
          max: 200
          unit_of_measurement: lx
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 2
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: switch.turn_on
    target: !input switch_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: switch.toggle
    target: !input switch_target
